### ISSUE TITLE
Error with rendering QR

### ISSUE THREAD

**Issue by ProjectPatatoe** [egg82/2FAPlus#4]
Tried to create a TOTP. It gave me a map which couldn't render.
2FAPlus - `2.3.15`
Spigot - `CraftBukkit version git-Spigot-1a3504a-84f3da3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)`
OS - Ubuntu Server 18.04
JRE - was OpenJDK 11, now Oracle 12 (same error)

This flooded the console after creating until I destroyed the map
```
[19:50:46 ERROR]: Could not render map using renderer me.egg82.tfaplus.renderers.ImageRenderer
java.lang.NoClassDefFoundError: Could not initialize class java.awt.GraphicsEnvironment$LocalGE
        at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:129) ~[?:?]
        at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181) ~[?:?]
        at org.bukkit.map.MapPalette.imageToBytes(MapPalette.java:191) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at org.bukkit.craftbukkit.v1_13_R2.map.CraftMapCanvas.drawImage(CraftMapCanvas.java:65) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at me.egg82.tfaplus.renderers.ImageRenderer.render(ImageRenderer.java:39) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.map.CraftMapView.render(CraftMapView.java:149) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.WorldMap$WorldMapHumanTracker.a(WorldMap.java:423) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.WorldMap.a(WorldMap.java:317) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.ItemWorldMap.a(ItemWorldMap.java:329) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.EntityPlayer.playerTick(EntityPlayer.java:385) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.PlayerConnection.tick(PlayerConnection.java:140) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:230) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:119) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:994) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by egg82** [comment]
After some quick discussion, an issue like that is usually due to the JRE (or its dependencies) not being installed correctly (which would affect more than just 2FA+)

It's difficult to tell without the full stacktrace/error though.

**Comment by ProjectPatatoe** [comment]
ok so turns out previously i was on OpenJDK 11. I've switched to Oracle Java 12 and rebuilt Spigot, same problem. How can I get a full stack trace?
(Oracle Java 8 is becoming increasingly difficult to get)

**Comment by egg82** [comment]
No need for Oracle's Java 8. Oracle's Java is based on OpenJDK/OpenJRE so will run fine with those.

**Comment by ProjectPatatoe** [comment]
ok. I do prefer to stay on openjdk, I'll switch back after resolving this, thanks. If it is a dependency issue, do you mean a missing lib? I'm on Ubuntu 18.04

**Comment by egg82** [comment]
It may be a missing lib, but the project also wan't compiled for 11 or 12. It's compiled on 8, as is Spigot (Paper is compiled on 8, 9, and 11 iirc)

**Comment by egg82** [comment]
Closing because it seems resolved. Re-open if needed.
